"""Create initial stock_details and stock_history tables

Revision ID: 9d7db63d67ef
Revises: 
Create Date: 2025-12-06 19:09:40.705570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d7db63d67ef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_details',
    sa.Column('isin', sa.String(length=20), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('instrument', sa.String(length=10), nullable=True),
    sa.Column('exchange', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('isin'),
    sa.UniqueConstraint('isin')
    )
    op.create_index(op.f('ix_stock_details_symbol'), 'stock_details', ['symbol'], unique=True)
    op.create_table('stock_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('stock_isin', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('series', sa.String(length=10), nullable=True),
    sa.Column('open', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('high', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('low', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('prev_close', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ltp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('close', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vwap', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('high_52w', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('low_52w', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('no_of_trades', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stock_isin'], ['stock_details.isin'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_isin', 'date', name='uix_stock_date')
    )
    op.create_index(op.f('ix_stock_history_date'), 'stock_history', ['date'], unique=False)
    op.create_index(op.f('ix_stock_history_stock_isin'), 'stock_history', ['stock_isin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_history_stock_isin'), table_name='stock_history')
    op.drop_index(op.f('ix_stock_history_date'), table_name='stock_history')
    op.drop_table('stock_history')
    op.drop_index(op.f('ix_stock_details_symbol'), table_name='stock_details')
    op.drop_table('stock_details')
    # ### end Alembic commands ###
